### ISSUE TITLE
Document how to use the bots and what can and cannot be expected

### ISSUE THREAD

**Issue by weedySeaDragon** [AgileVentures/asyncvoter-slack#13]
Provide some simple documentation that explains how to use the bots, what their features/capabilities are.

In no particular order, here are some random things I learned when trying to use them today:
- there are actually 2 different bots.  One of the is only for _all of the AgileVentures Slack instance_ and the other runs _1 per channel_
- using a bot means it's tied up and no one can use it to vote on anything else until you're done with it

How do you "run" each bot?
How do you "release" each bot?
How do you get the results?
What if you have trouble?  Can you kill/restart it?
Can you 'undo' or 'subtract' a vote or do you have to just re-do the whole vote?

What's the syntax?   Is there a help command or flag?

**Comment by tansaku** [comment]
thanks @weedySeaDragon - we need to take the old bot offline - the new one from @arreche that works one per channel is the replacement that we need to consolidate on.

I'm taking the old AsyncVoterBot that worked on DMs offline right now

**Comment by tansaku** [comment]
and yes, more detailed documentation required - it's not an allergy on documentation on our part - more a question of resources.  We're following an agile model of getting something bare bones up - now we have to flesh it out (including documentation) ... huge kudos to @arreche for putting in the effort to get us to this new and improved interface!

**Comment by weedySeaDragon** [comment]
I don't think there's an allergy to documentation. 
I'm just being an active user and giving my feedback.  :-)

From my perspective, this tool was made available to us (the shf-project), which is great.  But it came with no documentation and we didn't really know how to make it work for us.
(Just had a hangout today after our client meeting and 3 of us had the same questions:  We want to use this, we all were kind of unsure and said things like "how does that work again?"  "do we use the slash to get it to work?")

The good news is that users (me & others on shf-project) _want_ to use this!  It's evidence that your tool is actually being used, and people like it so much that they want _more_. :-)

== Real life asynchronous user feedback 

@arreche has already got #12 which will be a great start.
