### ISSUE TITLE
client id is hard coded in public/index.html

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/asyncvoter-slack#3]
ideally would come from environment variable

**Comment by arreche** [comment]
`CLIENT_ID` is not sensible data but It may cause confusion when it comes to deploy other instances of this code.

I see different choises:
1. Warning this duplication issue in the documentation.
2. Generating the landing page dynamically from the server side. 
3. Generating the landing page with a module builder such `webpack`.

What do you think?

**Comment by tansaku** [comment]
I think generate the landing page dynamically and inserting the correct client id
